baseURL = 'https://hackerspad.net'
languageCode = 'en-us'
title = 'Discover softwares, their alternatives, reviews, news, questions and comparisons.'
summarylength = 30
[taxonomies]
  platform = "platform"
  classification = "classification"

[permalinks]
  software = "/software/:filename/"

[params]
  description = "Software Alternatives,Reviews and Comparisions."
  contentBackgroundColor = "#f8f9fa"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#f8f9fe"
  navbarLinkColor = "#000"
  navbarLinkHoverColor = "#007bff"
  wrapperMaxWidth = "800px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = "UA-123456789-1"
  cookieConsent = false
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Classification"
  url = "/classification/"
  weight = 1
  [[menu.nav]]
  name = "Platforms"
  url = "/platform/"
  weight = 2

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2